### ISSUE TITLE
“Data Visualization Notes” not showing in the "New File" templates 

### ISSUE THREAD

**Issue by luiandresgonzalez** [kjhealy/socviz#4]
Hi, following the instructions given at section 2.2.2 of the book, when clicking "From template" at the sidebar, the "Data Visualization Notes" does not appear in the list. 

I'm using Version 1.1.463 of RStudio with R version 3.4.4 on Ubuntu MATE 18.04.

Library (socviz) is loaded before the procedure. 

I can find the template file in the socviz project folder under templates.

**Comment by kjhealy** [comment]
Hi, this was an error in the package that I've just fixed. If you reinstall it with `install_github("kjhealy/socviz")` the new version should work as expected.

**Comment by jtransue** [comment]
I just reinstalled socviz and I'm having the same problem (see screenshot take on 13 July 2020
<img width="948" alt="Screen Shot 2020-07-13 at 9 26 58 PM" src="https://user-images.githubusercontent.com/6074111/87373770-ed25ff00-c54f-11ea-8e6b-619a52836ba2.png">
)

**Comment by jtransue** [comment]
I got it to work by doing library(devtools).

Strangely (to me), earlier in the session something from devtools worked.
> devtools::install_github("kjhealy/socviz")
Downloading GitHub repo kjhealy/socviz@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: rlang  (0.4.6 -> 0.4.7) [CRAN]
5: tibble (3.0.2 -> 3.0.3) [CRAN]
6: pillar (1.4.4 -> 1.4.6) [CRAN]

This is what worked.
> library(devtools)
Loading required package: usethis
> devtools::install_github("kjhealy/socviz")
Skipping install of 'socviz' from a github remote, the SHA1 (539f679b) has not changed since last install.
  Use `force = TRUE` to force installation
> library(socviz)
>

**Comment by kjhealy** [comment]
That's a little odd. Notice how `socviz` isn't actually reinstalled there, just `rlang`, `tibble` and `pillar` were updated slightly. I wonder if there's an RStudio issue when it comes to finding newly-installed templates or something.
